### ISSUE TITLE
Script Merger descriptions cleanup

### ISSUE THREAD

**Issue by odelphi** [Nexus-Mods/extension-script-extender-error-check#2]
In the Script Merger program, when you open up the options window some of the descriptions are too long for the window so they extend past the window; therefore, you cannot read the full description. Suggest widening the options window about 20 pixels or allowing resizing. Also, the bottom "footnote" section of the main screen, where it lists # of mods found, is too narrow. It is cutting off about 3-4 pixels of the words.

**Comment by TanninOne** [comment]
I'm assuming that by "Script Merger" you mean this application: https://www.nexusmods.com/witcher3/mods/484/
That is a completely separate application from Vortex. You have to contact the author of that application to get things fixed there.

**Comment by odelphi** [comment]
I don't know which one I am meaning.  All I know is its the one that runs inside of Vortex after you deploy a mod.  A message pops up suggesting that you run the Script Merger.  When the screen comes up it says in the title bar "Script Merger v0.6.4".  I thought the new version of Vortex supposed to have Script Merger built-in, so I assumed it was a Vortex program.

**Comment by TanninOne** [comment]
Script Merger is a separate application, developed by a separate person. If you want your problems fixed you have to talk to them.
Just because Vortex automates _running_ an application doesn't mean we maintain it.

**Comment by odelphi** [comment]
Ok, Thank you.  I will contact the developer of the program.
